"""create quiz table

Revision ID: c3a075c7a25f
Revises: f9903645b107
Create Date: 2025-05-19 16:36:44.358627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a075c7a25f'
down_revision = 'f9903645b107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('summary_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    # ### end Alembic commands ###
