"""remove note column to highlight table

Revision ID: dad61deeab3a
Revises: ed1d988512aa
Create Date: 2025-05-18 16:53:25.822856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dad61deeab3a'
down_revision = 'ed1d988512aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
