"""create summary table

Revision ID: f9903645b107
Revises: 84c53a86b91f
Create Date: 2025-05-19 14:31:01.289780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9903645b107'
down_revision = '84c53a86b91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary',
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('highlight_ids', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary')
    # ### end Alembic commands ###
